---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-deployment
spec: 
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcatserver
    spec:
      containers:
      - name: tomcatserver
        image: tomcat
        ports:
        - name: tomcatport
          containerPort: 5000   
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatserver
  labels: 
    app: tomcatserver
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: tomcatserver
